export default ({
  state: {
    viewedGoods: [
      {
        id: 'id1',
        name: 'BXC',
        descr: 'Вытяжное устройство для механической системы вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'BXC_G2H1065',
      },
      {
        id: 'id0',
        name: 'G2H',
        descr: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'G2H_G2H1065',
      },
      {
        id: 'id2',
        name: 'GHN',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'GHN_G2H1065',
      }, {
        id: 'id023020',
        name: 'TDA',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'TDA_G2H1065',
      }, {
        id: 'id023021',
        name: 'BXC2',
        descr: 'Вытяжное устройство для механической системы вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'BXC2_G2H1065',
      },
      {
        id: 'id023022',
        name: 'G2H2',
        descr: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'G2H2_G2H1065',
      },
      {
        id: 'id023023',
        name: 'GHN2',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'GHN2_G2H1065',
      }, {
        id: 'id023024',
        name: 'TDA2',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'TDA2_G2H1065',
      }, {
        id: 'id023025',
        name: 'BXC3',
        descr: 'Вытяжное устройство для механической системы вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'BXC3_G2H1065',
      },
      {
        id: 'id023026',
        name: 'G2H3',
        descr: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'G2H3_G2H1065',
      },
      {
        id: 'id023027',
        name: 'GHN3',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'GHN3_G2H1065',
      }, {
        id: 'id023028',
        name: 'TDA3',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'TDA3_G2H1065',
      }, {
        id: 'id023029',
        name: 'BXC4',
        descr: 'Вытяжное устройство для механической системы вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'BXC4_G2H1065',
      },
      {
        id: 'id023030',
        name: 'G2H4',
        descr: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'G2H4_G2H1065',
      },
      {
        id: 'id023031',
        name: 'GHN4',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'GHN4_G2H1065',
      }, {
        id: 'id023032',
        name: 'TDA4',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'TDA4_G2H1065',
      }, {
        id: 'id023033',
        name: 'BXC5',
        descr: 'Вытяжное устройство для механической системы вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'BXC5_G2H1065',
      },
      {
        id: 'id023034',
        name: 'G2H5',
        descr: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'G2H5_G2H1065',
      },
      {
        id: 'id023035',
        name: 'GHN5',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'GHN5_G2H1065',
      }, {
        id: 'id023036',
        name: 'TDA5',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'TDA5_G2H1065',
      }, {
        id: 'id023037',
        name: 'BXC6',
        descr: 'Вытяжное устройство для механической системы вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'BXC6_G2H1065',
      },
      {
        id: 'id023038',
        name: 'G2H6',
        descr: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
        priceMin: 6848,
        priceMax: 56584,
        image: 'G2H6_G2H1065',
      },
      {
        id: 'id023039',
        name: 'GHN6',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'GHN6_G2H1065',
      }, {
        id: 'id023040',
        name: 'TDA6',
        descr: 'Вытяжное устройство с датчиком присутствия',
        priceMin: 6848,
        priceMax: 56584,
        image: 'TDA6_G2H1065',
      },
    ]
  },
  getters: {
    getViewedGoods(state) {
      return state.viewedGoods;
    },
  },
  mutations: {

  },
  actions: {
  },

})